#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Final_Year_Project-ESP32_Embedded_Software_Design

include $(IDF_PATH)/make/project.mk
